
id: ecos-config-type

name: { ru: Конфигурация, en: Config }

parentRef: emodel/type@data-list
formRef: uiserv/eform@config_ecosConfig
journalRef: uiserv/journal@ecosConfig

properties:
  alfType: config:ecosConfig
  alfRoot: /app:company_home/app:dictionary/cm:IDocsRoot/cm:ecos-config-root
