---
id: ecosConfig

name: { ru: Конфигурация Alfresco, en: Alfresco Config }

actions:
  - uiserv/action@edit

columns:
  - id: cm:title
  - id: config:key
  - id: config:value
  - id: cm:description
