---
id: products-and-services
name: { ru: Продукты и услуги, en: Products and services }

actions:
  - uiserv/action@edit

columns:
  - id: cm:title
  - id: pas:pricePerUnit
  - id: pas:entityUnit
  - id: pas:type
  - id: pas:currency

